name: Build TechDocs with DevHub TechDocs Publish Action

on:
    workflow_dispatch:
    push:
        branches: [ ${{ values.target_branch }} ]
        paths:
            - "mkdocs.yml"
            - "${{ values.docs_path }}/*"
    pull_request:
        branches: [ ${{ values.target_branch }} ]
        paths:
            - "mkdocs.yml"
            - "${{ values.docs_path }}/*"

jobs:
    test_techdocs_build_job:
        runs-on: ubuntu-latest

        name: A job to build and publish techdocs content
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Build TechDocs
                uses: bcgov/devhub-techdocs-publish@stable
                id: build_and_publish
                with:
                    publish: 'false'

