site_name: "${{ values.title }}"
site_description: "${{ values.description }}"
docs_dir: "docs"
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - md_in_html
    - mkpatcher:
          location: patcher.py
