site_name: "${{ values.title }}"
site_description: "${{ values.description }}"
docs_dir: "docs"
repo_url:  "${{ values.repo_url.host }}"
edit_uri: edit/main/docs/
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
