site_name: "${{ values.title }}"
site_description: "${{ values.description }}"
docs_dir: "docs"
repo_url: "https://${{ values.repo_url.host }}/${{ values.repo_url.owner }}/${{ values.repo_url.repo}}"
edit_uri: edit/main/docs/
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
