site_name: "${{ values.title }}"
site_description: "${{ values.description }}"
docs_dir: "docs"
repo_url:  "${{ values.repo_url }}"
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
