site_name: "${{ values.title }}"
site_description: "${{ values.description }}"
docs_dir: "docs"
repo_url:  "${{ values.repo_url }}"
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - ezlinks
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
    -   mkpatcher:
            location: patcher.py
