apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
    name: docs-template-v2
    title: DevHub Technical Documentation Template
    description: Create a new repository (or pull request) for technical documentation
    tags:
        - techdocs
        - markdown
        - developer-experience
        - core
spec:
    owner: "developer-experience"
    type: documentation
    parameters:
        -   title: Provide information about your documentation
            required:
                - title
                - description
            properties:
                title:
                    title: Title
                    type: string
                    description: A title for your documentation. For example, "Whizzbang Service Developer's Guide".
                    ui:autofocus: true
                description:
                    title: Description
                    type: string
                    description: A description for your documentation
                owner:
                    title: Owner
                    type: string
                    description: The team in GitHub that is developing the documentation, if there is one.
                    ui:field: OwnerPicker
                    ui:options:
                        allowArbitraryValues: false
                        allowedKinds:
                            - Group
        -   title: Provide information about your product (or service/component)
            properties:
                ministry:
                    title: Ministry
                    type: string
                    description: Name of the ministry associated with the product
                    enum:
                        - AF
                        - AG
                        - MCF
                        - CITZ
                        - ECC
                        - EMCR
                        - EMLI
                        - ENV
                        - FIN
                        - FOR
                        - HLTH
                        - HOUS
                        - IRR
                        - JEDI
                        - LBR
                        - MMHA
                        - MUNI
                        - PSFS
                        - PSSG
                        - SDPR
                        - TACS
                        - TRAN
                        - WLRS
                    enumNames:
                        - "Agriculture and Food"
                        - "Attorney General"
                        - "Children and Family Development"
                        - "Citizens' Services"
                        - "Education and Child Care"
                        - "Emergency Management and Climate Readiness"
                        - "Energy, Mines and Low Carbon Innovation"
                        - "Environment and Climate Change Strategy"
                        - "Finance"
                        - "Forests"
                        - "Health"
                        - "Housing"
                        - "Indigenous Relations & Reconciliation"
                        - "Jobs, Economic Development and Innovation"
                        - "Labour"
                        - "Mental Health and Addictions"
                        - "Municipal Affairs"
                        - "Post-Secondary Education and Future Skills"
                        - "Public Safety and Solicitor General"
                        - "Social Development and Poverty Reduction"
                        - "Tourism, Arts, Culture and Sport"
                        - "Transportation and Infrastructure"
                        - "Water, Land and Resource Stewardship"
                program_area:
                    title: Program area
                    type: string
                    description: Name of the program area associated with the product
                product_name:
                    title: Product name
                    type: string
                    description: The name of the product
                product_acronym:
                    title: Product acronym
                    type: string
                    description: An acronym used to identity the product, if there is one
                product_owner:
                    title: Product owner
                    type: string
                    description: Name of the individual in the Product Owner role for the product
                product_owner_email:
                    title: Product owner email
                    type: string
                    description: Email address of the individual in the Product Owner role for the product
                hosting_platform:
                    title: Hosting platform
                    type: string
                    description: Name of the technical platform where the product is hosted
                    default: Private-Cloud-Openshift
                    enum:
                        - Amazon-Web-Services
                        - Google-Cloud-Platform
                        - Microsoft-Azure
                        - On-Premise-Physical
                        - On-Premise-Virtual
                        - Private-Cloud-Openshift
                        - Other
                        - Unknown
                        - Not-Applicable
                    enumNames:
                        - 'Amazon Web Service'
                        - 'Google Cloud Platform'
                        - 'Microsoft Azure'
                        - 'On-premise virtual infrastructure'
                        - 'On-premise physical infrastructure'
                        - 'OpenShift private cloud'
                        - "Other platform that isn't listed"
                        - "Not sure"
                        - "Not applicable"
        -   title: Specify repository details
            required:
                - repoUrl
            properties:
                repoUrl:
                    title: Name of the repository that we will create to store your documentation
                    type: string
                    ui:field: RepoUrlPicker
                    ui:options:
                        requestUserCredentials: # this is super important - it causes the user to be prompted to log in to GitHub and/or authorize the required GH scopes.
                            secretsKey: USER_OAUTH_TOKEN
                            additionalScopes:
                                github:
                                    - workflow
                        allowedHosts:
                            - github.com
                        allowedOwners:
                            - bcgov
                repoExists:
                    title: Create pull request for an existing repository
                    type: boolean
            dependencies:
                repoExists:
                    allOf:
                        -   if:
                                properties:
                                    repoExists:
                                        const: true
                            then:
                                required:
                                    -   targetBranchName
                                    -   docsPath
                                properties:
                                    targetBranchName:
                                        title: Target branch name
                                        type: string
                                        description: The target branch name of the merge request
                                        default: main
                                    docsPath:
                                        title: Documentation subdirectory
                                        type: string
                                        description: The path to an existing documentation subdirectory. For example, "docs/src".
    steps:
        -   id: fetch-base
            name: Add files from skeleton and apply user-provided values.
            action: fetch:template
            input:
                url: ./skeleton
                values:
                    name: ${{ parameters.title | lower | replace(" ", "-") | replace("'", "") }}
                    title: ${{ parameters.title }}
                    description: ${{ parameters.description }}
                    destination: ${{ parameters.repoUrl | parseRepoUrl }}
                    repo_url: ${{ parameters.repoUrl | projectSlug }}
                    owner: ${{ parameters.owner }}
                    ministry: ${{ parameters.ministry }}
                    program_area: ${{ parameters.program_area }}
                    product_name: ${{ parameters.product_name }}
                    product_acronym: ${{ parameters.product_acronym }}
                    product_owner: ${{ parameters.product_owner }}
                    product_owner_email: ${{ parameters.product_owner_email }}
                    docs_path: ${{ parameters.docsPath if parameters.repoExists === true else 'docs' }}
                    target_branch: ${{ parameters.targetBranchName if parameters.repoExists === true else 'main' }}
        -   id: rename-files
            name: Rename docs folder to repo subdir if supplied
            if: ${{ parameters.repoExists === true and (parameters.docsPath !== 'docs' and parameters.docsPath !== 'docs/') }}
            action: fs:rename
            input:
                files:
                    -   from: "docs/index.md"
                        to: "${{ parameters.docsPath }}/index.md"
        -   id: create-catalog-file
            name: Create catalog file.
            action: catalog:write
            input:
                entity:
                    apiVersion: backstage.io/v1alpha1
                    kind: Component
                    metadata:
                        name: ${{ parameters.title | lower | replace(" ", "-") | replace("'", "") }}
                        title: ${{ parameters.title }}
                        description: ${{parameters.description }}
                        annotations:
                            github.com/project-slug: ${{ parameters.repoUrl | projectSlug }}
                            backstage.io/techdocs-ref: dir:.
                            bcgovpubcode.gov.bc.ca/ministry: ${{ parameters.ministry }}
                            bcgovpubcode.gov.bc.ca/program_area: ${{ parameters.program_area }}
                            bcgovpubcode.gov.bc.ca/product_name: ${{ parameters.product_name }}
                            bcgovpubcode.gov.bc.ca/product_acronym: ${{ parameters.product_acronym }}
                            bcgovpubcode.gov.bc.ca/product_owner: ${{ parameters.product_owner }}
                            developer.gov.bc.ca/source_template: "default/docs-template-v2"
                    spec:
                        type: documentation
                        lifecycle: experimental
                        owner: ${{ parameters.owner | default("developer-experience", true) }}
        -   id: fetch-action
            name: Add GitHub Actions workflow files.
            action: fetch:plain
            input:
                url: ../../shared/.github # pull from a shared location. The workflow lives in this location so we can reuse it access multiple templates instead of cutting and pasting it.
                targetPath: ./.github
        -   id: pubcode
            name: Template Pubcode
            action: fetch:template
            input:
                url: ../../shared/pubcode
                values:
                    name: ${{ parameters.product_name }}
                    description: ${{ parameters.description }}
                    destination: ${{ parameters.repoUrl | parseRepoUrl }}
                    ministry: ${{ parameters.ministry }}
                    program_area: ${{ parameters.program_area }}
                    product_name: ${{ parameters.product_name }}
                    product_acronym: ${{ parameters.product_acronym }}
                    product_owner: ${{ parameters.product_owner }}
                    hosting_platform: ${{ parameters.hosting_platform }}
        -   id: publish
            name: Publish
            if: ${{ parameters.repoExists !== true }}
            action: publish:github
            input:
                allowedHosts: [ "github.com" ]
                description: This is ${{ parameters.name }}
                repoUrl: ${{ parameters.repoUrl }}
                token: ${{ secrets.USER_OAUTH_TOKEN }} # this causes the GitHub publish to be performed as the logged-in user and reduces the required permissions of the app itself.
                repoVisibility: "public"
                defaultBranch: "main"
                gitCommitMessage: "DevHub creating new repository for TechDocs."
                gitAuthorName: ${{ user.entity.metadata.name }} # this likely won't populate properly we do some additional work on sign in to improve the default behaviour.
                gitAuthorEmail: ${{ user.entity.spec.profile.email }} # this likely won't work  populate properly until we do some additional work on sign in to improve the default behaviour.
                hasProjects: false
                hasWiki: false
                topics: [ "techdocs", "devhub" ]
        -   id: publish
            name: Publish
            if: ${{ parameters.repoExists === true }}
            action: publish:github:pull-request
            input:
                repoUrl: ${{ parameters.repoUrl }}
                title: "DevHub publishing pull request"
                branchName: "DevHub-publishing-pr-branch"
                description: "This pull request will add the files required to publish documentation on DevHub"
                token: ${{ secrets.USER_OAUTH_TOKEN }} # this causes the GitHub publish to be performed as the logged-in user and reduces the required permissions of the app itself.
                targetBranchName: ${{ parameters.targetBranchName }}
                commitMessage: "DevHub creating new files for TechDocs."
                update: true
    output:
        links:
            -   title: ${{ 'New Pull Request' if parameters.repoExists === true else 'Repository' }}
                url: ${{ steps.publish.output.remoteUrl }}
        text:
            -   title: Congratulations and next steps...
                content: |
                    **Congratulations, you've made a new GitHub ${{ 'pull request' if parameters.repoExists === true else 'repository' }} for your technical documentation!**

                    ## Here are the next steps you can take to get your documentation published in DevHub:

                    * check out the contents of [your ${{ 'new pr' if parameters.repoExists === true else 'new repo' }}](${{ steps.publish.output.remoteUrl }}) ${{ 'especially the [README file](${{ steps.publish.output.remoteUrl }}/README.md) and the [example home page](${{ steps.publish.output.remoteUrl }}/docs/index.md)' if parameters.repoExists === false }}
                    * check out [our Content Partner Guide](https://developer.gov.bc.ca) for info on "how this all works" and for creating your documentation
                    * add your additional pages to the repository

                    When you'd like to have your documentation published in DevHub, [contact the Developer Experience Team](mailto:developer.experience@gov.bc.ca) and we'll work with you to set things up. Note that we have a "preview" environment and a production environment, and you'll be in control of how and when your content is published to each.

