apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
    name: quickstart-openshift
    title: QuickStart for OpenShift
    description: Create a new repo using the OpenShift QuickStart project
    tags:
        - quickstart
        - openshift
        - community-wizard
spec:
    owner: "developer-experience"
    type: service
    parameters:
        -   $yaml: https://github.com/bcgov/devhub-templates/blob/main/shared/common-yaml/catalog-info-component-parameters.yaml
        -   $yaml: https://github.com/bcgov/devhub-templates/blob/main/shared/common-yaml/pubcode-parameters.yaml
        -   title: Provide configuration details
            required:
                # - usePostGIS
                - backend
            properties:
                # usePostGIS:
                #     title: Switch to PostGIS instead of Postgres
                #     type: boolean
                #     ui:widget: radio
                backend:
                    title: Select the backend stack
                    type: string
                    default: backend-default
                    enum:
                        - backend-default
                        # - backend-go
                        - backend-java
                        - backend-py
                    enumNames:
                        - "JavaScript/TypeScript"
                        # - "Go with Fiber"
                        - "Java with Quarkus, Cloud Native"
                        - "Python with FastAPI"
        -   title: Specify repository details
            required:
                - repo
            properties:
                repo:
                    title: Name of the new QuickStart for OpenShift repository that we will create
                    type: string
                    ui:field: RepoUrlPicker
                    ui:options:
                        requestUserCredentials: # this is super important - it causes the user to be prompted to log in to GitHub and/or authorize the required GH scopes.
                            secretsKey: USER_OAUTH_TOKEN
                            additionalScopes:
                                github:
                                    - workflow
                        allowedHosts:
                            - github.com
                        allowedOwners:
                            - bcgov
                owner:
                    title: GitHub team (optional)
                    type: string
                    description: The GitHub team that is developing the project, if there is one.
                    ui:field: OwnerPicker
                    ui:options:
                        allowArbitraryValues: false
                        catalogFilter:
                            - kind: [ Group ]
                              metadata.namespace: bcgov
    steps:
        -   $yaml: https://github.com/bcgov/devhub-templates/blob/main/shared/common-yaml/catalog-info-component-action.yaml
        -   id: add-quickstart-project
            name: Add openshift quickstart project
            action: fetch:plain
            input:
                url: https://github.com/bcgov/quickstart-openshift/tree/main
        -   id: rm-default-backend
            name: remove default backend
            if: ${{ parameters.backend != 'backend-default' }}
            action: fs:delete
            input:
                files:
                    - backend
        -   id: add-backend-plugins
            name: Add backend plugin
            if: ${{ parameters.backend != 'backend-default' }}
            action: fetch:plain
            input:
                url: https://github.com/bcgov/quickstart-openshift-backends/tree/main/${{ parameters.backend }}
                targetPath: 'backend'
        # -   id: use-postgis
        #     name: Switch the database to PostGIS
        #     if: ${{ parameters.usePostGIS }}
        #     action: fs:rename
        #     input:
        #         files:
        #             -   from: ./database/postgis/Dockerfile
        #                 to: ./database/Dockerfile
        #                 overwrite: true
        -   id: publish
            name: Publish
            action: publish:github
            input:
                allowedHosts: [ "github.com" ]
                description: ${{ parameters.description }} # "New QuickStart for OpenShift repo"
                repoUrl: ${{ parameters.repo }}
                token: ${{ secrets.USER_OAUTH_TOKEN }} # this causes the GitHub publish to be performed as the logged-in user and reduces the required permissions of the app itself.
                repoVisibility: "public"
                defaultBranch: "main"
                gitCommitMessage: "DevHub creating new files for QuickStart for OpenShift."
                gitAuthorName: ${{ user.entity.metadata.product_name }} # this likely won't populate properly we do some additional work on sign in to improve the default behaviour.
                gitAuthorEmail: ${{ user.entity.spec.profile.email }} # this likely won't work  populate properly until we do some additional work on sign in to improve the default behaviour.
                hasProjects: false
                hasWiki: false
                topics: [ "devhub", "openshift" ]
                collaborators:
                    -   team: ${{ parameters.owner if parameters.owner }}
                        access: ${{ 'admin' if parameters.owner }}
    output:
        links:
            -   title: New Repository
                url: ${{ steps.publish.output.remoteUrl }}
        text:
            -   title: Congratulations and next steps...
                content: |
                    **Congratulations, you've made a new GitHub repository for your project!**

                    ## Here are the next steps you can take:

                    * check out the contents of [your new repo](${{ steps.publish.output.remoteUrl }})
                    * check out [the QuickStart for OpenShift ReadMe](https://github.com/bcgov/quickstart-openshift)

                    This project is provided by NRIDS Architecture and Forestry Digital Services, courtesy of the Government of British Columbia.

                    * NRID's [Kickstarter Guide](https://bcgov.github.io/nr-architecture-patterns-library/docs/Agile%20Team%20Kickstarter) (via. Confluence, links may be internal)
                    * [OpenShift Backends for Go, Java and Python](https://github.com/bcgov/quickstart-openshift-backends)
